### ISSUE TITLE
add 永康市

### ISSUE THREAD

**Issue by Cyhlnj** [getActivity/ProvinceJson#11]
永康市一般指永康。永康，古称丽州，浙江省金华市代管县级市，位于浙江省中部的低山丘陵地区。
百度百科：https://baike.baidu.com/item/%E6%B0%B8%E5%BA%B7/3441691?fromtitle=%E6%B0%B8%E5%BA%B7%E5%B8%82&fromid=10098746&fr=aladdin

**Comment by getActivity** [comment]
收到，已经纠正，多谢小伙子的提醒
