### ISSUE TITLE
发现 缺少 镇江市的 扬中市、句容市

### ISSUE THREAD

**Issue by itransit** [getActivity/ProvinceJson#14]
发现 缺少 镇江市的 扬中市、句容市，参考民政部的在线地址：
http://xzqh.mca.gov.cn/defaultQuery?shengji=%BD%AD%CB%D5%CA%A1%A3%A8%CB%D5%A3%A9&diji=%D5%F2%BD%AD%CA%D0&xianji=%D1%EF%D6%D0%CA%D0

**Comment by getActivity** [comment]
已经纠正，多谢小伙子的提醒
