### ISSUE TITLE
临平区，隶属于浙江省杭州市。

### ISSUE THREAD

**Issue by sunviacde** [getActivity/ProvinceJson#15]
2021年04月09日，浙江省人民政府发布《关于调整杭州市部分行政区划的通知》。设立杭州市临平区，临平区人民政府驻临平街道西大街33号。
https://baike.baidu.com/item/%E4%B8%B4%E5%B9%B3%E5%8C%BA/56654046?fr=aladdin

**Comment by getActivity** [comment]
收到，数据已经更新了，多谢小伙子的提醒。
