### ISSUE TITLE
关于重庆市开县，目前已经改为开州区

### ISSUE THREAD

**Issue by tangchangqiang** [getActivity/ProvinceJson#5]
2016年6月8日，国务院批复同意撤销开县，设立重庆市开州区 。
2016年7月22日，开州区正式挂牌成立。
2018年8月17日，开州区实现脱贫摘帽。

百度百科：https://baike.baidu.com/item/%E5%BC%80%E5%B7%9E%E5%8C%BA/1463471?fromtitle=%E5%BC%80%E5%B7%9E&fromid=7973964&fr=aladdin

**Comment by getActivity** [comment]
已经纠正，多谢老哥提醒

**Comment by tangchangqiang** [comment]
目前，梁平县已经改为梁平区

2016年11月24日，国务院正式签发《国务院关于同意重庆市调整部分行政区划的批复》：同意撤销梁平县，设立梁平区。
2017年1月10日，梁平区人民政府正式成立。

https://baike.baidu.com/item/%E6%A2%81%E5%B9%B3%E5%8C%BA/19947574?fr=aladdin
